### ISSUE TITLE
Consider having links to external applications display in a new tab

### ISSUE THREAD

**Issue by servilla** [PASTAplus/web-x#12]
Jon Ide suggested that links that open a new application, such as ezEML, should open in a new tab so that it is clear to users that the application is functionally different from web-x. To do so, one would use the `target="_blank"` and `rel="noopener noreferrer"` attributes within the anchor element.

For example:
```
<a href="https://ezeml.edirepository.org/eml/" target="_blank" rel="noopener noreferrer">ezEML</a>
```

**Comment by clnsmth** [comment]
@servilla I'd like this extended to any external resource, not only applications.
