### ISSUE TITLE
Uploading Data with Static Links ezEML section could be improved

### ISSUE THREAD

**Issue by kzollove** [PASTAplus/web-x#24]
The ezEML section should demonstrate or at least give mention to "Add a table from scratch" ezEML functionality. This would be how tables are added in the case they are too large for the file to be loaded.

Of particular interest are how to calculate MD5, file size, and number of rows in table.

**Comment by clnsmth** [comment]
Nice @kzollove. Do you mind handling this (i.e. submitting a PR to content-x)?

**Comment by kzollove** [comment]
I'm on it!
