### ISSUE TITLE
NSF credit missing in footer

### ISSUE THREAD

**Issue by cgries** [PASTAplus/web-x#36]
This blurb needs to go into the footer: Copyright 2022 [Environmental Data Initiative](https://edirepository.org/). This material is based upon work supported by the National Science Foundation under grants #1931143 and #1931174. Any opinions, findings, conclusions, or recommendations expressed in the material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation. Please [contact us](mailto:info@edirepository.org) with questions, comments, or for technical assistance regarding this web site or the Environmental Data Initiative. Please read our [privacy policy](....) to know what information we collect about you and to understand your privacy rights.

**Comment by clnsmth** [comment]
Thanks @cgries. The proposed text takes up quite a bit of real estate. Can we pair it down to something like `This material is based upon work supported by the National Science Foundation under Award Numbers #1931143 and #1931174`? 

Should we also add the NSF logo to the list of affiliates in the footer?

**Comment by cgries** [comment]
sure that's fine for the footer. But the full text needs to be somewhere on the website as per NSF. Scroll down on this page: https://www.nsf.gov/pubs/gpg/nsf04_23/6.jsp to see the instructions and decide where they should go.

**Comment by clnsmth** [comment]
This issue is partially fixed by PASTAplus/content-x@a756852f035a2dd7add90b815d1e9fabcdf59c88

**Comment by clnsmth** [comment]
The remainder of this fix is now in main at 6bb06359c904066210531c32b2e4e1cf85b0c926.
