### ISSUE TITLE
Code formatting is inactive

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/web-x#4]
[The example in this section of the website](https://web-x.edirepository.org/resources/create-a-data-catalog#catalogs-for-obfs-members) is wrapped in code formatting but is being interpreted literally. Seems like the CSS controlling this feature is not working.

**Comment by clnsmth** [comment]
Actually, this appears to be an issue in `build.py` when converting from .md to .html. Additionally, tables are not translated correctly. See: https://github.com/PASTAplus/web-x/blob/main/templates/data/example.html.

**Comment by servilla** [comment]
The root issue is in the Python `markdown` package - it apparently does not recognize Git markdown's ``` code format directive. The alternative is to encapsulate the HTML example in `<pre>...</pre>` elements. In addition, all HTML significant characters must be encoded per HTML rules, for example:

```
<pre>
&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;title&gt;Data Catalog&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;

&lt;h1&gt;Adirondack Ecological Center - Data&lt;/h1&gt;
&lt;object type=&quot;text/html&quot; width=&quot;100%&quot; height=&quot;100%&quot;
data=&quot;https://vocab.lternet.edu/ezcatalog/datacat.php?searchString=*&amp;scope=*
&amp;constraint=%28coordinates%253A%2522IsWithin%28ENVELOPE%28-75%2C-73%2C45%2C43%29%29%2522%29%2B
OR%2B%28*%3A*%2BAND%2Btitle%3A(ADIRONDACK)%29%2BOR%2B%28*%3A*%2BAND%2Bkeyword%3A(ADIRONDACK)%29
&amp;form=htmltablejssearch&quot;&gt;
&lt;/object&gt;

&lt;/body&gt;
&lt;/html&gt;
</pre>
```

**Comment by clnsmth** [comment]
@servilla It turns out the markdown package has a 'fenced_code' extension that will handle the multi-line code block use case. I'm pushing this fix along with a modification to the CSS to support inline code highlighting.
